# Generated by Django 3.1.5 on 2021-01-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videopost',
            options={'ordering': ['title']},
        ),
    ]
