# Generated by Django 3.1.5 on 2021-01-09 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Upload', '0002_auto_20210108_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
                ('video_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_post_comment', to='App_Upload.videopost')),
            ],
            options={
                'ordering': ('-comment_date',),
            },
        ),
    ]
